# Dockerfile: extiende Airflow e instala tus dependencias
FROM apache/airflow:2.8.1

# Copiar requirements.txt
COPY requirements.txt .

# Instalar dependencias como pandera y pytest
RUN pip install --no-cache-dir -r requirements.txt
