# Dockerfile: Extend Airflow and install your dependencies
FROM apache/airflow:2.8.1

# Copy requirements.txt
COPY requirements.txt .

# Install dependencies like pandera and pytest
RUN pip install --no-cache-dir -r requirements.txt
